"""
Django settings for sourcecloze project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
from split_settings.tools import optional, include
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# URL = "https://sourcecloze.zdv.uni-mainz.de"
base_settings = [
    'settings_base.py',
    'settings_logging.py',
    'settings_tests.py',
    BASE_DIR+'/authentication/settings_authentication.py',
    # optional('local_settings.py')
]

# Include settings:
include(*base_settings)

